sudo: false

language: python
python:
  - "2.7"

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
    - python-numpy

before_install:
  - export GR1CVERSION=0.10.2
  - curl -sO http://vehicles.caltech.edu/snapshots/gr1c/gr1c-$GR1CVERSION.tar.gz
  - expr `shasum -a 256 gr1c-$GR1CVERSION.tar.gz|cut -d ' ' -f1` = 12762f7fcebca12ce9d36f20ea26d644872a2d6ae616a34d922f23c66bfed1ca
  - tar -xzf gr1c-$GR1CVERSION.tar.gz && cd gr1c-$GR1CVERSION && ./get-deps.sh
  - make -j2 cudd && make -j2 all && make check
  - export PATH=`pwd`:$PATH
  - cd ..
  - pip install scipy

install:
  - pip install .

script: ./run_tests.py

notifications:
  email: false